# Generated by Django 6.0.6 on 2026-06-13 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pełna nazwa (np. Bitcoin, Dolar)')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Skrót / Symbol (np. BTC, USD)')),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Kryptowaluta'), ('FIAT', 'Waluta tradycyjna (FIAT)')], default='CRYPTO', max_length=10, verbose_name='Rodzaj waluty')),
                ('api_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID w API (np. bitcoin)')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCache',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.asset', verbose_name='Waluta')),
                ('price_pln', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Aktualny kurs w PLN')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja kursu')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Kupno'), ('SELL', 'Sprzedaż')], max_length=4, verbose_name='Typ operacji')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Ilość (ile sztuk)')),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cena za 1 sztukę (w PLN)')),
                ('date', models.DateTimeField(verbose_name='Data i czas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.asset', verbose_name='Wybrana waluta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
