# Generated by Django 6.0.6 on 2026-06-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallettransaction_quantity_assetcache_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_type',
        ),
    ]
